version: "3.9"

services:
    example.rest_api:
        image: example.rest_api
        build: 
            context: ./api_rest/
            target: development
        ports: 
            - 8000:8000
        volumes: 
            - ./api_rest/src/:/app


