version: "3.9"

services:
    example.rest_api:
        image: example.rest_api
        build: 
            context: ./api_rest/
            target: production
        ports: 
            - 8000:8000
